repos:
- repo: local
  hooks:
    - id: run-migration
      name: Run Laravel Migration
      entry: php artisan migrate:fresh --seed
      language: system
      pass_filenames: false
    - id: run-composer-install
      name: Run Composer Install
      entry: composer install
      language: system
      pass_filenames: false
    - id: run-pnpm-install
      name: Run pnpm Install
      entry: pnpm install
      language: system
      pass_filenames: false