services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: leconfe-app

    working_dir: /app

    volumes:
      - .:/app

    stdin_open: true
    tty: true

    ports:
      - "8000:8000"

    command: php artisan serve --host=0.0.0.0 --port=8000

    environment:
      - DB_HOST=db

    depends_on:
      - db

  db:
    image: mariadb:11

    container_name: leconfe-db

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leconfe
      MYSQL_USER: leconfe
      MYSQL_PASSWORD: leconfe

    ports:
      - "3306:3306"

    volumes:
      - leconfe_db_data:/var/lib/mysql

  postgres:
    image: postgres:15
    container_name: leconfe-postgres
    environment:
      POSTGRES_DB: leconfe_test
      POSTGRES_USER: leconfe
      POSTGRES_PASSWORD: leconfe
    ports:
      - "5432:5432"
    volumes:
      - leconfe_postgres_data:/var/lib/postgresql/data

volumes:
  leconfe_db_data:
  leconfe_postgres_data: