import defaultTheme from 'tailwindcss/defaultTheme'

export default {
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: {
                    50: 'var(--primary-50)',
                    100: 'var(--primary-100)',
                    200: 'var(--primary-200)',
                    300: 'var(--primary-300)',
                    400: 'var(--primary-400)',
                    500: 'var(--primary-500)',
                    600: 'var(--primary-600)',
                    700: 'var(--primary-700)',
                    800: 'var(--primary-800)',
                    900: 'var(--primary-900)',
                    950: 'var(--primary-950)',
                },
                danger: {
                    50: 'var(--danger-50)',
                    100: 'var(--danger-100)',
                    200: 'var(--danger-200)',
                    300: 'var(--danger-300)',
                    400: 'var(--danger-400)',
                    500: 'var(--danger-500)',
                    600: 'var(--danger-600)',
                    700: 'var(--danger-700)',
                    800: 'var(--danger-800)',
                    900: 'var(--danger-900)',
                    950: 'var(--danger-950)',
                },
                gray: {
                    50: 'var(--gray-50)',
                    100: 'var(--gray-100)',
                    200: 'var(--gray-200)',
                    300: 'var(--gray-300)',
                    400: 'var(--gray-400)',
                    500: 'var(--gray-500)',
                    600: 'var(--gray-600)',
                    700: 'var(--gray-700)',
                    800: 'var(--gray-800)',
                    900: 'var(--gray-900)',
                    950: 'var(--gray-950)',
                },
                success: {
                    50: 'var(--success-50)',
                    100: 'var(--success-100)',
                    200: 'var(--success-200)',
                    300: 'var(--success-300)',
                    400: 'var(--success-400)',
                    500: 'var(--success-500)',
                    600: 'var(--success-600)',
                    700: 'var(--success-700)',
                    800: 'var(--success-800)',
                    900: 'var(--success-900)',
                    950: 'var(--success-950)',
                },
                warning: {
                    50: 'var(--warning-50)',
                    100: 'var(--warning-100)',
                    200: 'var(--warning-200)',
                    300: 'var(--warning-300)',
                    400: 'var(--warning-400)',
                    500: 'var(--warning-500)',
                    600: 'var(--warning-600)',
                    700: 'var(--warning-700)',
                    800: 'var(--warning-800)',
                    900: 'var(--warning-900)',
                    950: 'var(--warning-950)',
                },
                info: {
                    50: 'var(--info-50)',
                    100: 'var(--info-100)',
                    200: 'var(--info-200)',
                    300: 'var(--info-300)',
                    400: 'var(--info-400)',
                    500: 'var(--info-500)',
                    600: 'var(--info-600)',
                    700: 'var(--info-700)',
                    800: 'var(--info-800)',
                    900: 'var(--info-900)',
                    950: 'var(--info-950)',
                },
            },
            fontFamily: {
                sans: [
                    '"Twemoji Country Flags"',
                    'var(--font-family)',
                    ...defaultTheme.fontFamily.sans,
                ],
            },
        },
    },
    content: [
        './app/Administration/**/*.php',
        './app/Filament/**/*.php',
        './app/Livewire/**/*.php',
        './app/Panel/**/*.php',
        './resources/views/components/**/*.blade.php',
        './resources/views/frontend/scheduledConference/pages/**/*.blade.php',
        './resources/views/administration/**/*.blade.php',
        './resources/views/examples/**/*.blade.php',
        './resources/views/filament/**/*.blade.php',
        './resources/views/forms/**/*.blade.php',
        './resources/views/panel/**/*.blade.php',
        './resources/views/vendor/**/*.blade.php',
        './resources/views/infolists/**/*.blade.php',
        './resources/views/forms/**/*.blade.php',
        './resources/views/tables/**/*.blade.php',
        './vendor/awcodes/filament-tiptap-editor/resources/**/*.blade.php',
        './vendor/filament/**/*.blade.php',
    ],
    plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
}
