name: fix-code-style

on:
  push:

jobs:
  fix-code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # - name: Set up PNPM
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 8
      - name: Install dependencies
        run: |
          composer install --no-interaction
      - name: Run Pint
        run: composer pint
      # - name: Run Prettier
      #   run: pnpm run prettier
      - name: Pull changes
        run: git pull
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: >
            chore: fix code style
